### ISSUE TITLE
onPictureChoosed return Base64?

### ISSUE THREAD

**Issue by ugene123** [brunon80/expo-image-crop#10]
Hey, thanks for creating this. This isn't an issue but more of a suggestion - can you make it so onPictureChoosed also returns the cropped image base64 value?

It would be very helpful to have both uri and base64. 

I know you can set ImageManipulator.manipulateAsync() to return base64 so I don't think this should be too much to ask for :)

Thank you

**Comment by hungdangdt** [comment]
try this code when you wait update
`let base64_str = await FileSystem.readAsStringAsync(
			uri,
			{
				encoding: FileSystem.EncodingType.Base64
			});`

**Comment by brunon80** [comment]
Hi, on version 0.2.13 onPictureChoosed now returns a base64, check readme to see new options

https://www.npmjs.com/package/expo-image-crop?activeTab=readme
