### ISSUE TITLE
ExpoSDK33 issues

### ISSUE THREAD

**Issue by iKrushYou** [brunon80/expo-image-crop#11]
Hey, I was able to get this working on an SDK32 project but now i'm on 33 and things aren't working. I just keep getting a bunch of "module not found" errors after importing
`import { ImageManipulator } from 'expo-image-crop'`
and then I go and add the imports that it mentions and finally I'm left with the error
`The Expo SDK requires Expo to run...`

**Comment by milkyway044** [comment]
Don't work with Expo33

**Comment by brunon80** [comment]
I've been very busy on other projects recently and I didn't pay much attention to that, in this case, I upgraded to Expo SDK 35, but I didn't test very well, so if you can test and evaluate if everything is ok, I'll make it available on npm
