### ISSUE TITLE
squareAspect

### ISSUE THREAD

**Issue by GitHubGreg** [brunon80/expo-image-crop#12]
Thanks for this valuable tool! I see squareAspect used in [this example](https://github.com/brunon80/expo-image-crop/commit/80a078f86cb3e98bf599d7495bf63ffb150ebb50). When I add it as a prop it doesn't actually force a square aspect ratio.

**Comment by GitHubGreg** [comment]
I also found that defining custom texts in btnTexts doesn't work either.
As per your npm notice, I am using version 0.2.8, so this may be why.

**Comment by brunon80** [comment]
The new version 0.2.11 this feature is available!

**Comment by Aryk** [comment]
Was the fixed square aspect feature removed? I don't see it anymore in the code.

Fixing the width and heigh "can" make a square, but then the user can't zoom in or out...

**Comment by Aryk** [comment]
Nevermind just saw the warning message about staying on 0.2.17, but the  pinching and zooming of the crop box is very jerky on that version...
