### ISSUE TITLE
This library is not compatible with expo 34

### ISSUE THREAD

**Issue by edoantonioco** [brunon80/expo-image-crop#13]
Version: 0.2.8

Latest expo versions has been separating modules away from expo module, and this time was the opportunity to imagemanipulator module.

![Screenshot_1566765226](https://user-images.githubusercontent.com/5560824/63655464-7cae9d80-c745-11e9-9858-59b9ddb3f838.png)

I installed this in my project (expo install expo-image-manipulator), but the bug is still there, which I think it means its the library the one that needs to get updated.

So because of this, its not possible to crop any photo. 
Can this please be fixed?

**Comment by edoantonioco** [comment]
A workaround is to go to
node_modules/expo-image-crop/example/manipulator/ImageManipulator.js
and replace
import { ImageManipulator } from 'expo'
with 
import * as ImageManipulator from 'expo-image-manipulator'

but I hope this gets fixed in the library

**Comment by edoantonioco** [comment]
Edition: After seeing the example in the main page, I think this has already being done in the latest version. But since latest version doesnt work properly then I have to use version 0.2.8

**Comment by edoantonioco** [comment]
Is this library still maintained at all?

**Comment by brunon80** [comment]
I've been very busy on other projects recently and I didn't pay much attention to that, in this case, I upgraded to Expo SDK 35, but I didn't test very well, so if you can test and evaluate if everything is ok, I'll make it available on npm

**Comment by edoantonioco** [comment]
latest version is still 0.2.10. Is it ok?

In this version it says
`Unable to resolve "expo-ads-admob" from "node_modules/expo-image-crop/example/node_modules/expo/build/Expo.js"`

which can probably be fixed by installing the required dependency in this package.

**Comment by edoantonioco** [comment]
Can you please make a 0.2.11 release with these changes?

**Comment by brunon80** [comment]
I didn't have much time to test, but I believe you tested it and it worked, so here it is:
https://www.npmjs.com/package/expo-image-crop?activeTab=readme

**Comment by edoantonioco** [comment]
yeah it works great now. Only thing I have to do to make this running (just like previous version) is installing expo-image-manipulator into my project
