### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by cloudtenlabs** [brunon80/expo-image-crop#18]
Possible Unhandled Promise Rejection (id: 0):
Object {
  "code": "EABI36_0_0RCTERRORDOMAIN0",
  "domain": "ABI36_0_0RCTErrorDomain",
  "message": "Cannot load a photo library asset with no URL",
  "nativeStackIOS": Array [
    "0   Exponent                            0x000000010286becb ABI36_0_0RCTJSErrorFromCodeMessageAndNSError + 79",
    "1   Exponent                            0x000000010286be49 ABI36_0_0RCTJSErrorFromNSError + 209",
    "2   Exponent                            0x0000000102828623 __50-[ABI36_0_0RCTModuleMethod processMethodSignature]_block_invoke_4.90 + 70",
    "3   Exponent                            0x0000000102882e3f __59-[ABI36_0_0RCTImageLoader getImageSizeForURLRequest:block:]_block_invoke + 649",
    "4   Exponent                            0x000000010287faf3 __127-[ABI36_0_0RCTImageLoader _loadImageOrDataWithURLRequest:size:scale:resizeMode:progressBlock:partialLoadBlock:completionBlock:]_block_invoke + 225",
    "5   Exponent                            0x00000001028801aa __127-[ABI36_0_0RCTImageLoader _loadImageOrDataWithURLRequest:size:scale:resizeMode:progressBlock:partialLoadBlock:completionBlock:]_block_invoke_2.184 + 43",
    "6   Exponent                            0x000000010289a0d1 -[ABI36_0_0RCTPhotoLibraryImageLoader loadImageForURL:size:scale:resizeMode:progressHandler:partialLoadHandler:completionHandler:] + 429",
    "7   Exponent                            0x000000010287ff0f __127-[ABI36_0_0RCTImageLoader _loadImageOrDataWithURLRequest:size:scale:resizeMode:progressBlock:partialLoadBlock:completionBlock:]_block_invoke.183 + 264",
    "8   libdispatch.dylib                   0x00007fff5223e848 _dispatch_call_block_and_release + 12",
    "9   libdispatch.dylib                   0x00007fff5223f7b9 _dispatch_client_callout + 8",
    "10  libdispatch.dylib                   0x00007fff52245526 _dispatch_lane_serial_drain + 707",
    "11  libdispatch.dylib                   0x00007fff52245f5c _dispatch_lane_invoke + 388",
    "12  libdispatch.dylib                   0x00007fff5224fff9 _dispatch_workloop_worker_thread + 626",
    "13  libsystem_pthread.dylib             0x00007fff524636fc _pthread_wqthread + 290",
    "14  libsystem_pthread.dylib             0x00007fff52462827 start_wqthread + 15",
  ],
  "userInfo": Object {
    "NSLocalizedDescription": "Cannot load a photo library asset with no URL",
  },
}

**Comment by brunon80** [comment]
can you describe your use case so i can simulate?

**Comment by cloudtenlabs** [comment]
sorry for your kind response. actually I couldn't use this library because there was too many flickering, so I built a new library

**Comment by brunon80** [comment]
That Cool! it will be a pleasure to test.
