### ISSUE TITLE
image crop aspect ratio

### ISSUE THREAD

**Issue by alivanov** [brunon80/expo-image-crop#2]
Hi,
how can I set crop aspect ratio like https://docs.expo.io/versions/latest/sdk/imagepicker/#arguments?
Also it would be awesome to have an option to disable an image rotation.

Thanks

**Comment by brunon80** [comment]
Currently there are no such aspect ratio options and a way to hide actions, so I will categorize them as improvements, hopefully in the near future add them, but if you want, you can do a pull request and further improve this module. Thank you!

**Comment by ahansson89** [comment]
Would love to see this added. I have a usecase where I need some standard 16:9, 9:16 and 1:1 aspect ratio's cropped, but I also have odd aspect ratio's like 5:4 and 1:2 aspect ratio's that I need to be able to crop.
