### ISSUE TITLE
100% Crashing

### ISSUE THREAD

**Issue by wheelie33** [brunon80/expo-image-crop#61]
If I add this package and the linked code, it ONLY crashes when deployed to Test Flight and Google Play Console.  NEVER on the Expo Go app.

https://gist.github.com/wheelie33/676a194ce6ee05703187a7821a24e715

**Comment by Joshmatjjen** [comment]
Look for an alternative library..  it is no longer being maintained

**Comment by wheelie33** [comment]
OK
