### ISSUE TITLE
[Feature request] Language support

### ISSUE THREAD

**Issue by edoantonioco** [brunon80/expo-image-crop#9]
This library is great, but its only in english. If I were able to change it to spanish would be great. 

Another option would be for each person to manually translate it manually every time the library is used (through some parameter for each one of 'crop', 'rotate', etc, or through a json like some other libraries does)

**Comment by brunon80** [comment]
Great suggestion, I agree with you and soon I must add the option, thank you!

**Comment by brunon80** [comment]
@edoantonioco done
https://www.npmjs.com/package/expo-image-crop/v/0.2.10

**Comment by edoantonioco** [comment]
@brunon80 This last 0.2.10 update broke things. Here is the output:

Unable to resolve "react-native-maps" from "node_modules/expo-image-crop/example/node_modules/expo/build/Expo.js"

I reinstalled the package and now that happens

**Comment by brunon80** [comment]
You are right, I encountered problems with versions 0.2.10 and 0.2.9 that I will correct in ASAP, I recommend using version 0.2.8

**Comment by edoantonioco** [comment]
0.2.8 doesnt work with current expo
